/*
 * Copyright (c) 2025 Arthur Araujo
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

package cc.wordview.api.service.implementation;

import cc.wordview.api.exception.SubtitleNotFoundException;
import cc.wordview.api.runtime.cache.LyricsCache;
import cc.wordview.api.runtime.cache.SubtitlesCache;
import cc.wordview.api.runtime.cache.TextTrackCache;
import cc.wordview.api.service.TextTracksServiceInterface;
import cc.wordview.wordfind.WordFind;
import cc.wordview.wordfind.exception.LyricsNotFoundException;
import jakarta.annotation.PostConstruct;
import org.schabi.newpipe.extractor.NewPipe;
import org.schabi.newpipe.extractor.StreamingService;
import org.schabi.newpipe.extractor.exceptions.ExtractionException;
import org.schabi.newpipe.extractor.stream.StreamInfo;
import org.schabi.newpipe.extractor.stream.SubtitlesStream;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;

import java.io.IOException;
import java.util.Objects;

@Service
public class TextTracksService implements TextTracksServiceInterface {
    private static final Logger logger = LoggerFactory.getLogger(TextTracksService.class);
    private static StreamingService YTService;

    private final WordFind client = new WordFind();

    @Autowired
    private TextTrackCache cache;

    @Override
    public String getLyrics(String id, String trackName, String artistName, String langTag) throws LyricsNotFoundException {
        String lyrics = cache.get(id);

        if (lyrics == null) {
            lyrics = getYouTubeSubtitle(id, langTag);
        }

        if (lyrics == null) {
            lyrics = getLyricsExternal(trackName, artistName);
        }

        if (Objects.equals(lyrics, "WEBVTT\n\n# This WEBVTT was converted from LRC and might contain errors\n\n")) {
            throw new LyricsNotFoundException("Unable to find lyrics for %s".formatted(trackName));
        }

        cache.put(id, lyrics);
        return lyrics;
    }

    @Override
    public String getSubtitle(String id, String langTag) throws SubtitleNotFoundException {
        String subtitle = cache.get(id);

        if (subtitle == null) {
            subtitle = getYouTubeSubtitle(id, langTag);
        }

        if (subtitle == null) {
            throw new SubtitleNotFoundException("Unable to find any subtitles for the video %s".formatted(id));
        }

        cache.put(id, subtitle);

        return subtitle;
    }


    private String getYouTubeSubtitle(String id, String lang) {
        try {
            StreamInfo info = StreamInfo.getInfo(YTService, "https://youtube.com/watch?v=" + id);

            for (SubtitlesStream subtitle : info.getSubtitles()) {
                if (subtitle.isAutoGenerated()) continue;

                if (Objects.equals(subtitle.getLanguageTag(), lang)) {
                    String url = subtitle.getContent().replace("&fmt=ttml", "&fmt=vtt");

                    return new RestTemplate().getForObject(url, String.class);
                }
            }
        } catch (Exception e) {
            logger.error("Failed to retrieve subtitles from YouTube", e);
        }

        return null;
    }

    @PostConstruct
    private void initNewPipe() throws ExtractionException {
        YTService = NewPipe.getService(0);
    }

    @PostConstruct
    private void preloadLyrics() throws IOException {
        cache.init();
    }

    @Override
    public String getLyricsExternal(String trackName, String artistName) throws LyricsNotFoundException {
        return client.find(trackName, artistName, true, null, null);
    }
}
